# Generated by Django 3.2.9 on 2021-12-21 01:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_auto_20211219_1457'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='new',
            options={'ordering': ['dayCreate']},
        ),
        migrations.RenameField(
            model_name='new',
            old_name='created',
            new_name='dayCreate',
        ),
    ]
