# Generated by Django 3.2.9 on 2021-12-21 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_rename_new_id_comment_new'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='date_cmt',
            new_name='date_created',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='user_cmt',
            new_name='user_comment',
        ),
    ]
